# On k-Nearest Neighbors Modeling

The idea of k-nearest neighbors is to make predictions about the values of your dependent variable of interest based on the values of that variable for _nearby_ points.

We have a dataset of people who regularly check the weather. We're purveyors of SmartWatches, and we're interested in whether people would be likely to check their weather on their SmartWatch, if they had one.

As predictors of this, we'll focus on gender and age group.

In [55]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
# weather = pd.read_csv('../../../../../data/weather-check/weather-check.csv')
weather = pd.read_csv('weather-check.csv')

In [56]:
weather.head()

RespondentID Do you typically check a daily weather report?  \
0    3887201482                                            Yes   
1    3887159451                                            Yes   
2    3887152228                                            Yes   
3    3887145426                                            Yes   
4    3887021873                                            Yes   

             How do you typically check the weather?  \
0              The default weather app on your phone   
1              The default weather app on your phone   
2              The default weather app on your phone   
3              The default weather app on your phone   
4  A specific website or app (please provide the ...   

  A specific website or app (please provide the answer)  \
0                                                  -      
1                                                  -      
2                                                  -      
3                                                  -      
4                                         Iphone app      

  If you had a smartwatch (like the soon to be released Apple Watch), how likely or unlikely would you be to check the weather on that device?  \
0                                        Very likely                                                                                             
1                                        Very likely                                                                                             
2                                        Very likely                                                                                             
3                                    Somewhat likely                                                                                             
4                                        Very likely                                                                                             

       Age What is your gender?  \
0  30 - 44                 Male   
1  18 - 29                 Male   
2  30 - 44                 Male   
3  30 - 44                 Male   
4  30 - 44                 Male   

  How much total combined money did all members of your HOUSEHOLD earn last year?  \
0                                 $50,000 to $74,999                                
1                               Prefer not to answer                                
2                               $100,000 to $124,999                                
3                               Prefer not to answer                                
4                               $150,000 to $174,999                                

         US Region  
0   South Atlantic  
1                -  
2  Middle Atlantic  
3                -  
4  Middle Atlantic

In [57]:
# Let's take the 'if you had a smartwatch' column as our target
# ... and rename it.
weather.rename({'If you had a smartwatch (like the soon to be released Apple Watch), how likely or unlikely would you be to check the weather on that device?':'watch'}, axis=1, inplace=True)


In [58]:
# Let's look at the different values of this column.
weather['watch'].value_counts()


Very likely          362
Somewhat likely      274
Very unlikely        208
Somewhat unlikely     73
-                     11
Name: watch, dtype: int64

In [59]:
# Let's build a dictionary and replace these text
# values with numbers. We'll go ahead and fill
# nulls with 0. (Is this a good idea in this case?)
watch_dict = {'Very likely':4, 'Somewhat likely':3,
             'Somewhat unlikely':2, 'Very likely':1, '-':0}


In [60]:
weather['watch'] = weather['watch'].map(watch_dict)

In [61]:
weather['watch'].fillna(0, inplace=True)

In [62]:
weather['watch'].value_counts()

1.0    362
3.0    274
0.0    219
2.0     73
Name: watch, dtype: int64

In [63]:
weather.columns

Index(['RespondentID', 'Do you typically check a daily weather report?',
       'How do you typically check the weather?',
       'A specific website or app (please provide the answer)', 'watch', 'Age',
       'What is your gender?',
       'How much total combined money did all members of your HOUSEHOLD earn last year?',
       'US Region'],
      dtype='object')

In [64]:
# Let's do the same thing with the 'what is your gender'
# column: rename and remap
weather.rename({'What is your gender?':'gender'}, axis=1 , inplace=True)

In [65]:
# values
gender_dict = {'Female':1,'Male':0, '-':0}
weather.gender.value_counts()

Female    527
Male      389
-          12
Name: gender, dtype: int64

In [66]:
# remap
weather['gender'] = weather['gender'].map(gender_dict)


In [67]:
weather['gender'].head()

0    0
1    0
2    0
3    0
4    0
Name: gender, dtype: int64

In [68]:
# Age column: check values
weather['Age'].value_counts()


45 - 59    278
60+        258
30 - 44    204
18 - 29    176
-           12
Name: Age, dtype: int64

In [9]:
# Let's replace these values
# with numbers also. We'll fill
# in nulls with 0. Is this
# appropriate in this case?




In [69]:
# Let's use gender and age as our predictors.
# Our target will be 'watch'.
age_dict = {'60+':4, '45 - 59':3, '30 - 44':2, '18 - 29':1, '-':0}
weather['Age'] = weather['Age'].map(age_dict)

In [70]:
# Age column: check values
weather['Age'].value_counts()


3    278
4    258
2    204
1    176
0     12
Name: Age, dtype: int64

In [72]:
X = weather[['gender', 'Age']]
y = weather['watch']

In [73]:
# Train-test splitting
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [74]:
# Now let's fit a knn classifier to our training data
# I had the best luck with p=100, n_neighbors=1
knn = KNeighborsClassifier(n_neighbors=1, p=100)


In [75]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=100,
           weights='uniform')

In [78]:
# We can score it on our test set.
# What is the score here?
knn.score(X_test, y_test) #Accuracy


0.3448275862068966

In [79]:
preds = knn.predict(X_test)

In [82]:
import numpy as np

In [90]:
# Manual way
sum(preds == np.array(y_test)) / len(y_test)

0.3448275862068966

In [91]:
# Let's use the predict_proba() method on a possible input
knn.predict_proba([[1,1]])


array([[0., 0., 0., 1.]])

In [92]:
# Let's import the confusion matrix metric and construct
# a matrix for our data
from sklearn.metrics import confusion_matrix


In [94]:
confusion_matrix(y_test, knn.predict(X_test))

array([[12, 28,  6, 13],
       [12, 54,  4, 23],
       [ 2,  9,  0,  6],
       [11, 34,  4, 14]])

In [95]:
12+54+0+14

80

In [93]:
knn.classes_

array([0., 1., 2., 3.])

In [14]:
106 / 232

0.45689655172413796

## Now: Question: How the heck did this work?

More precisely:
- What are these different parameters? (Especially: 'metric', 'p',
    'weights', and 'n_neighbors')
- How is distance calculated? (What is 'Minkowski'?)